services:
  client:
    build: 
      context: .
      dockerfile: ./DockerFile
    ports:
      - 80:3000
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PUBLIC_APP_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - TMDB_BEARER=${TMDB_BEARER}
      - NEXT_PUBLIC_TMDB_BEARER=${TMDB_BEARER}